apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: booking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:21.0
          args: ["start", "--hostname=booking.local", "--http-enabled=true"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_HTTP_RELATIVE_PATH
              value: "/"
            - name: KC_HOSTNAME
              value: "booking.local"
            - name: KC_HOSTNAME_PORT
              value: "80"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY
              value: "edge"
            - name: KC_FRONTEND_URL
              value: "http://booking.local"
            - name: KC_SPI_X_FRAME_OPTIONS_PROVIDER
              value: "allow-from-origin"
            - name: KC_SPI_X_FRAME_OPTIONS_ALLOW_ORIGIN
              value: "http://localhost:3000"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: booking-app
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
