apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: booking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "userdb"
          volumeMounts:
            - name: user-db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: user-db-data
          persistentVolumeClaim:
            claimName: user-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: booking-app
spec:
  selector:
    app: user-db
  ports:
    - port: 5432
      targetPort: 5432
